### ISSUE TITLE
there are more ideas for you

### ISSUE THREAD

**Issue by makc** [baphomet-berlin/jQuery-basic-arithmetic-plugin#3]
at http://jsperf.com/jquery-arithmetic-plugin

**Comment by petruavram** [comment]
The power is real. Also the performance much greater than potato

**Comment by cbrandolino** [comment]
pls send pull request to jsperf to add a merge button and i will merge your contrib, cant do it via command line. 

re:performance @petruavram is perfectly right it's faster than typing them on my ti calculator and then there's no risk that i click on cos and everything gets wierd.
