### ISSUE TITLE
Additional operations

### ISSUE THREAD

**Issue by pauldraper** [baphomet-berlin/jQuery-basic-arithmetic-plugin#4]
I know this is only the *basic arithmetic* plugin, but would it be possible to add other common math operations, like exponentation and absolute value?

I find myself needing to do these things quite often, but jQuery lacks support for them.

**Comment by cbrandolino** [comment]
sorry but javascript is not the best lang for advanced mathematics because floating point so we'd rather stick to classics like "plus" "minus" "star" and "slash" than chase all edge cases with too many syllables
