### ISSUE TITLE
Not enough jQuery

### ISSUE THREAD

**Issue by benjamingr** [baphomet-berlin/jQuery-basic-arithmetic-plugin#5]
-1 you should add more jQuery to this plugin.

**Comment by awalGarg** [comment]
-1 you should add more jQuery to this issue

**Comment by towc** [comment]
- it's way too useful, doesn't fit in jQuery's style
- the structure makes too much sense
- no [hadoken waves](http://i.imgur.com/BtjZedW.jpg) can be drawn using this plugin, too linear (yes, that's PHP, can't find the jQuery image)

**Comment by benjamingr** [comment]
Also, please change all `if` conditions to be in ternary to fit the jQuery source code style better.

**Comment by awalGarg** [comment]
Or better use the following plugin:

```javascript
$.ternary = function (ifthis, thenthis, elsethis) {
    return ifthis() ? thenthis() : elsethis();
}
```

**Comment by awalGarg** [comment]
@benjamingr you should use the above plugin it is very good use

**Comment by borisdiakur** [comment]
@awalGarg you should use this plugin in your plugin:

```javascript
$.condition = function (ifthis) {
    return ifthis();
}
```

**Comment by morkro** [comment]
Nice plugins guys, but they still miss one fundamental jQuery plugin:

```
$.return = function (returnthis) {
	return returnthis();
}
```

Please consider updating. It's also available on Bower.

**Comment by cbrandolino** [comment]
@morkro sorry but functional programming is a dying fad we will stay with our time-tested procedural jquery thanks tho
