### ISSUE TITLE
Unit test

### ISSUE THREAD

**Issue by kononenko-a-m** [baphomet-berlin/jQuery-basic-arithmetic-plugin#6]
I think plugin is not stable enough, can you please provide test coverage, in order to be sure that it's work as it should?

Thanks for your hard work, on this wonderful plugin!

**Comment by strugee** [comment]
Does commit ebe9bb417ccb8175c202c4953c33945ae26b91b5 not have what you're looking for?

**Comment by cbrandolino** [comment]
@strugee is right, u can run the tests by copying and pasting on w3schools javascript console and putting numbers in. its the only webscale system i found to test bc u can test as many numbers as u want. you will prob need a calculator to check.

thanks and dont forget 2 like and subscribe!
